Class {
	#name : 'GbxKeyedElement',
	#superclass : 'Object',
	#instVars : [
	],
	#classVars : [
	],
	#category : 'GemStone-GBS-Bootstrap',
	#package : 'GemStone-GBS-Bootstrap'
}

{ #category : 'accessing' }
GbxKeyedElement >> of: anObject key: aKey keyName: aKeyName value: aValue valueName: aValueName
[
	"VisualWorks compatibility stub"
]

{ #category : 'comparing' }
GbxKeyedElement >> = anObject
[
	"VisualWorks compatibility stub"
	^false
]

{ #category : 'accessing' }
GbxKeyedElement >> basicValueDelegate
[
	"VisualWorks compatibility stub"
	^nil
]

{ #category : 'accessing' }
GbxKeyedElement >> displayString
[
	"VisualWorks compatibility stub"
	^''
]

{ #category : 'accessing' }
GbxKeyedElement >> key
[
	"VisualWorks compatibility stub"
	^nil
]

{ #category : 'accessing' }
GbxKeyedElement >> keyDelegate
[
	"VisualWorks compatibility stub"
	^nil
]

{ #category : 'accessing' }
GbxKeyedElement >> keyDelegate: anObject
[
	"VisualWorks compatibility stub"
]

{ #category : 'accessing' }
GbxKeyedElement >> keyName: aString
[
	"VisualWorks compatibility stub"
]

{ #category : 'accessing' }
GbxKeyedElement >> partName
[
	"VisualWorks compatibility stub"
	^''
]

{ #category : 'accessing' }
GbxKeyedElement >> refresh
[
	"VisualWorks compatibility stub"
]

{ #category : 'accessing' }
GbxKeyedElement >> sameTypeEquals: anObject
[
	"VisualWorks compatibility stub"
	^false
]

{ #category : 'accessing' }
GbxKeyedElement >> text
[
	"VisualWorks compatibility stub"
	^''
]

{ #category : 'accessing' }
GbxKeyedElement >> value
[
	"VisualWorks compatibility stub"
	^nil
]

{ #category : 'accessing' }
GbxKeyedElement >> value: anObject
[
	"VisualWorks compatibility stub"
]

{ #category : 'accessing' }
GbxKeyedElement >> valueDelegate
[
	"VisualWorks compatibility stub"
	^nil
]

{ #category : 'accessing' }
GbxKeyedElement >> valueDelegate: anObject
[
	"VisualWorks compatibility stub"
]

{ #category : 'accessing' }
GbxKeyedElement >> valueName: aString
[
	"VisualWorks compatibility stub"
]
