Class {
	#name : 'GbxSegmentedPageDriver',
	#superclass : 'Object',
	#instVars : [
	],
	#classVars : [
	],
	#category : 'GemStone-GBS-Bootstrap',
	#package : 'GemStone-GBS-Bootstrap'
}

{ #category : 'accessing' }
GbxSegmentedPageDriver >> computeSegmentList
[
	"VisualWorks compatibility stub"
	^#()
]

{ #category : 'accessing' }
GbxSegmentedPageDriver >> markSegmentCached: anObject ifBetween: start and: end
[
	"VisualWorks compatibility stub"
]

{ #category : 'accessing' }
GbxSegmentedPageDriver >> segmentSelectionChanged
[
	"VisualWorks compatibility stub"
]
