Class {
	#name : 'GbxTextEditorInspector',
	#superclass : 'Object',
	#instVars : [
	],
	#classVars : [
	],
	#category : 'GemStone-GBS-Bootstrap',
	#package : 'GemStone-GBS-Bootstrap'
}

{ #category : 'testing' }
GbxTextEditorInspector >> gbxIsGbsInspector
[
	"VisualWorks compatibility stub"
	^true
]

{ #category : 'accessing' }
GbxTextEditorInspector >> tabLabel
[
	"VisualWorks compatibility stub"
	^'Text Editor'
]

{ #category : 'accessing' }
GbxTextEditorInspector >> documentHolder
[
	"VisualWorks compatibility stub"
	^nil
]

{ #category : 'accessing' }
GbxTextEditorInspector >> initialize: anObject
[
	"VisualWorks compatibility stub"
]

{ #category : 'accessing' }
GbxTextEditorInspector >> refresh
[
	"VisualWorks compatibility stub"
]

{ #category : 'accessing' }
GbxTextEditorInspector >> textAccepted: aString
[
	"VisualWorks compatibility stub"
]
