Class {
	#name : 'TextEditorInspector',
	#superclass : 'Object',
	#instVars : [
	],
	#classVars : [
	],
	#category : 'GemStone-GBS-Bootstrap',
	#package : 'GemStone-GBS-Bootstrap'
}

{ #category : 'testing' }
TextEditorInspector >> gbxIsGbsInspector
[
	"VisualWorks compatibility stub"
	^true
]

{ #category : 'accessing' }
TextEditorInspector >> tabLabel
[
	"VisualWorks compatibility stub"
	^'Text Editor'
]

{ #category : 'accessing' }
TextEditorInspector >> documentHolder
[
	"VisualWorks compatibility stub"
	^nil
]

{ #category : 'accessing' }
TextEditorInspector >> initialize: anObject
[
	"VisualWorks compatibility stub"
]

{ #category : 'accessing' }
TextEditorInspector >> refresh
[
	"VisualWorks compatibility stub"
]

{ #category : 'accessing' }
TextEditorInspector >> textAccepted: aString
[
	"VisualWorks compatibility stub"
]
