#!/usr/bin/env bash
set -euo pipefail

. "$(dirname "$0")/lane_common.sh"

VM="${PHARO_VM:-/Users/tariq/Documents/Pharo/vms/130-x64/Pharo.app/Contents/MacOS/Pharo}"
SRC_IMAGE="${1:-/Users/tariq/Documents/Pharo/images/Pharo 13.0 - clean/Pharo 13.0 - clean.image}"
WORK_DIR="${2:-$(dirname "${SRC_IMAGE}")}"
WORK_IMAGE="not-created"
JSON_SUMMARY="${GBS_JSON_SUMMARY:-0}"
THRESHOLD_FILE="${GBS_REPLICATION_LIVE_THRESHOLDS_FILE:-./scripts/replication_live_thresholds.env}"
if [[ -f "${THRESHOLD_FILE}" ]]; then
  # shellcheck disable=SC1090
  . "${THRESHOLD_FILE}"
fi
CONNECTOR_MAX_MS="${GBS_REPLICATION_LIVE_CONNECTOR_MAX_MS:-${REPLICATION_LIVE_CONNECTOR_MAX_MS:-1000}}"
CLAMPED_MAX_MS="${GBS_REPLICATION_LIVE_CLAMPED_MAX_MS:-${REPLICATION_LIVE_CLAMPED_MAX_MS:-500}}"
DIRTY_STORE_MAX_MS="${GBS_REPLICATION_LIVE_DIRTY_STORE_MAX_MS:-${REPLICATION_LIVE_DIRTY_STORE_MAX_MS:-2000}}"
CLAMPED_FETCHES_MIN="${GBS_REPLICATION_LIVE_CLAMPED_FETCHES_MIN:-${REPLICATION_LIVE_CLAMPED_FETCHES_MIN:-1}}"
CLAMPED_FETCHES_MAX="${GBS_REPLICATION_LIVE_CLAMPED_FETCHES_MAX:-${REPLICATION_LIVE_CLAMPED_FETCHES_MAX:-3}}"
CLAMPED_FALLBACKS_MAX="${GBS_REPLICATION_LIVE_CLAMPED_FALLBACKS_MAX:-${REPLICATION_LIVE_CLAMPED_FALLBACKS_MAX:-0}}"
NATIVE_DIRTY_STORE_FLUSHES_MIN="${GBS_REPLICATION_LIVE_NATIVE_DIRTY_STORE_FLUSHES_MIN:-${REPLICATION_LIVE_NATIVE_DIRTY_STORE_FLUSHES_MIN:-1}}"
DIRTY_OBJECTS_FLUSHED_MIN="${GBS_REPLICATION_LIVE_DIRTY_OBJECTS_FLUSHED_MIN:-${REPLICATION_LIVE_DIRTY_OBJECTS_FLUSHED_MIN:-3}}"
EXPORT_SET_QUEUED_AFTER_MAX="${GBS_REPLICATION_LIVE_EXPORT_SET_QUEUED_AFTER_MAX:-${REPLICATION_LIVE_EXPORT_SET_QUEUED_AFTER_MAX:-0}}"

emit_summary() {
  local result="$1"
  local code="$2"
  local connector_ms="${3:-0}"
  local clamped_ms="${4:-0}"
  local dirty_store_ms="${5:-0}"
  local clamped_fetches="${6:-0}"
  local clamped_fallbacks="${7:-0}"
  local native_flushes="${8:-0}"
  local dirty_objects="${9:-0}"
  local export_before="${10:-0}"
  local export_after="${11:-0}"
  local json_payload markdown_payload
  echo "REPLICATION_LIVE_SUMMARY result=${result} code=${code} connector_ms=${connector_ms} clamped_ms=${clamped_ms} dirty_store_ms=${dirty_store_ms} clamped_traversal_fetches=${clamped_fetches} clamped_traversal_fallbacks=${clamped_fallbacks} native_dirty_store_flushes=${native_flushes} dirty_objects_flushed=${dirty_objects} export_set_queued_before=${export_before} export_set_queued_after=${export_after} connector_max_ms=${CONNECTOR_MAX_MS} clamped_max_ms=${CLAMPED_MAX_MS} dirty_store_max_ms=${DIRTY_STORE_MAX_MS} threshold_file=${THRESHOLD_FILE} work_image=${WORK_IMAGE}"
  printf -v json_payload '{"result":"%s","code":"%s","connector_ms":"%s","clamped_ms":"%s","dirty_store_ms":"%s","clamped_traversal_fetches":"%s","clamped_traversal_fallbacks":"%s","native_dirty_store_flushes":"%s","dirty_objects_flushed":"%s","export_set_queued_before":"%s","export_set_queued_after":"%s","connector_max_ms":"%s","clamped_max_ms":"%s","dirty_store_max_ms":"%s","threshold_file":"%s","work_image":"%s"}' \
    "$(gbs_json_escape "${result}")" \
    "$(gbs_json_escape "${code}")" \
    "$(gbs_json_escape "${connector_ms}")" \
    "$(gbs_json_escape "${clamped_ms}")" \
    "$(gbs_json_escape "${dirty_store_ms}")" \
    "$(gbs_json_escape "${clamped_fetches}")" \
    "$(gbs_json_escape "${clamped_fallbacks}")" \
    "$(gbs_json_escape "${native_flushes}")" \
    "$(gbs_json_escape "${dirty_objects}")" \
    "$(gbs_json_escape "${export_before}")" \
    "$(gbs_json_escape "${export_after}")" \
    "$(gbs_json_escape "${CONNECTOR_MAX_MS}")" \
    "$(gbs_json_escape "${CLAMPED_MAX_MS}")" \
    "$(gbs_json_escape "${DIRTY_STORE_MAX_MS}")" \
    "$(gbs_json_escape "${THRESHOLD_FILE}")" \
    "$(gbs_json_escape "${WORK_IMAGE}")"
  if [[ "${JSON_SUMMARY}" == "1" ]]; then
    printf 'REPLICATION_LIVE_SUMMARY_JSON %s\n' "${json_payload}"
  fi
  gbs_write_json_summary_file "replication-live-summary.json" "${json_payload}"
  printf -v markdown_payload '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n' \
    '# Replication Live Validation' \
    "" \
    "- result: \`${result}\`" \
    "- code: \`${code}\`" \
    "- connector install: \`${connector_ms} ms\`" \
    "- clamped traversal fetch: \`${clamped_ms} ms\`, GciClampedTrav calls \`${clamped_fetches}\`, fallbacks \`${clamped_fallbacks}\`" \
    "- dirty-store flush: \`${dirty_store_ms} ms\`, native flushes \`${native_flushes}\`, dirty objects \`${dirty_objects}\`" \
    "- export-set queues: before \`${export_before}\`, after \`${export_after}\`" \
    "- thresholds: connector \`${CONNECTOR_MAX_MS} ms\`, clamped \`${CLAMPED_MAX_MS} ms\`, dirty-store \`${DIRTY_STORE_MAX_MS} ms\`" \
    "- threshold file: \`${THRESHOLD_FILE}\`" \
    "- work image: \`${WORK_IMAGE}\`" \
    "" \
    "Generated by \`make replication-live\`."
  gbs_write_evidence_file "replication-live-summary.md" "${markdown_payload}"
  gbs_append_summary_line "### Replication Live Validation"
  gbs_append_summary_line "- result: \`${result}\`"
  gbs_append_summary_line "- code: \`${code}\`"
  gbs_append_summary_line "- connector install: \`${connector_ms} ms\`"
  gbs_append_summary_line "- clamped traversal fetch: \`${clamped_ms} ms\`, GciClampedTrav calls \`${clamped_fetches}\`, fallbacks \`${clamped_fallbacks}\`"
  gbs_append_summary_line "- dirty-store flush: \`${dirty_store_ms} ms\`, native flushes \`${native_flushes}\`, dirty objects \`${dirty_objects}\`"
  gbs_append_summary_line "- export-set queues: before \`${export_before}\`, after \`${export_after}\`"
  gbs_append_summary_line "- thresholds: connector \`${CONNECTOR_MAX_MS} ms\`, clamped \`${CLAMPED_MAX_MS} ms\`, dirty-store \`${DIRTY_STORE_MAX_MS} ms\`"
}

extract_summary_field() {
  local line="$1"
  local field="$2"
  printf '%s\n' "${line}" | sed -n "s/.* ${field}=\\([^ ]*\\).*/\\1/p" | tail -1
}

replication_required_live_env_vars() {
  printf '%s\n' \
    GS_USER \
    GS_PASS \
    GEMSTONE
}

replication_missing_required_live_env_vars() {
  local var missing=""
  while IFS= read -r var; do
    [[ -n "${var}" ]] || continue
    if [[ -z "${!var:-}" ]]; then
      if [[ -n "${missing}" ]]; then
        missing="${missing},${var}"
      else
        missing="${var}"
      fi
    fi
  done < <(replication_required_live_env_vars)
  printf '%s\n' "${missing}"
}

print_replication_live_excerpt() {
  local output="$1"
  if [[ "${GBS_VERBOSE_LIVE_OUTPUT:-0}" == "1" ]]; then
    printf '%s\n' "${output}"
    return 0
  fi
  printf '%s\n' "${output}" | grep -E '^(Using work image:|LIVE_PREFLIGHT_(BEGIN|SUMMARY|OK|FAIL|SKIP|STONE_OK|NETLDI_OK|TOPAZ_LOGIN_OK|GCI_LOGIN_OK|MISSING_ENV)|PROBE_(CONFIG|LOGIN_OK|EVAL_RESULT)|REPLICATION_LIVE_(VALIDATION|SUMMARY))' || true
}

check_latency_threshold() {
  local label="$1"
  local value="$2"
  local max="$3"
  if [[ ! "${value}" =~ ^[0-9]+$ ]]; then
    emit_summary "FAIL" "REPLICATION_LIVE_BAD_${label}_METRIC" "${CONNECTOR_MS:-0}" "${CLAMPED_MS:-0}" "${DIRTY_STORE_MS:-0}" "${CLAMPED_FETCHES:-0}" "${CLAMPED_FALLBACKS:-0}" "${NATIVE_FLUSHES:-0}" "${DIRTY_OBJECTS:-0}" "${EXPORT_BEFORE:-0}" "${EXPORT_AFTER:-0}"
    echo "Replication live metric ${label} is not a non-negative integer: ${value}" >&2
    exit 1
  fi
  if [[ ! "${max}" =~ ^[0-9]+$ ]]; then
    emit_summary "FAIL" "REPLICATION_LIVE_BAD_${label}_THRESHOLD" "${CONNECTOR_MS:-0}" "${CLAMPED_MS:-0}" "${DIRTY_STORE_MS:-0}" "${CLAMPED_FETCHES:-0}" "${CLAMPED_FALLBACKS:-0}" "${NATIVE_FLUSHES:-0}" "${DIRTY_OBJECTS:-0}" "${EXPORT_BEFORE:-0}" "${EXPORT_AFTER:-0}"
    echo "Replication live threshold ${label} is not a non-negative integer: ${max}" >&2
    exit 1
  fi
  if (( value > max )); then
    emit_summary "FAIL" "REPLICATION_LIVE_${label}_THRESHOLD_EXCEEDED" "${CONNECTOR_MS:-0}" "${CLAMPED_MS:-0}" "${DIRTY_STORE_MS:-0}" "${CLAMPED_FETCHES:-0}" "${CLAMPED_FALLBACKS:-0}" "${NATIVE_FLUSHES:-0}" "${DIRTY_OBJECTS:-0}" "${EXPORT_BEFORE:-0}" "${EXPORT_AFTER:-0}"
    echo "Replication live metric ${label}=${value}ms exceeded threshold ${max}ms." >&2
    exit 1
  fi
}

check_count_threshold() {
  local label="$1"
  local value="$2"
  local max="$3"
  if [[ ! "${value}" =~ ^[0-9]+$ || ! "${max}" =~ ^[0-9]+$ ]]; then
    emit_summary "FAIL" "REPLICATION_LIVE_BAD_${label}_COUNT" "${CONNECTOR_MS:-0}" "${CLAMPED_MS:-0}" "${DIRTY_STORE_MS:-0}" "${CLAMPED_FETCHES:-0}" "${CLAMPED_FALLBACKS:-0}" "${NATIVE_FLUSHES:-0}" "${DIRTY_OBJECTS:-0}" "${EXPORT_BEFORE:-0}" "${EXPORT_AFTER:-0}"
    echo "Replication live count ${label} or threshold is not a non-negative integer: value=${value} max=${max}" >&2
    exit 1
  fi
  if (( value > max )); then
    emit_summary "FAIL" "REPLICATION_LIVE_${label}_COUNT_THRESHOLD_EXCEEDED" "${CONNECTOR_MS:-0}" "${CLAMPED_MS:-0}" "${DIRTY_STORE_MS:-0}" "${CLAMPED_FETCHES:-0}" "${CLAMPED_FALLBACKS:-0}" "${NATIVE_FLUSHES:-0}" "${DIRTY_OBJECTS:-0}" "${EXPORT_BEFORE:-0}" "${EXPORT_AFTER:-0}"
    echo "Replication live count ${label}=${value} exceeded threshold ${max}." >&2
    exit 1
  fi
}

check_count_minimum() {
  local label="$1"
  local value="$2"
  local min="$3"
  if [[ ! "${value}" =~ ^[0-9]+$ || ! "${min}" =~ ^[0-9]+$ ]]; then
    emit_summary "FAIL" "REPLICATION_LIVE_BAD_${label}_MIN_COUNT" "${CONNECTOR_MS:-0}" "${CLAMPED_MS:-0}" "${DIRTY_STORE_MS:-0}" "${CLAMPED_FETCHES:-0}" "${CLAMPED_FALLBACKS:-0}" "${NATIVE_FLUSHES:-0}" "${DIRTY_OBJECTS:-0}" "${EXPORT_BEFORE:-0}" "${EXPORT_AFTER:-0}"
    echo "Replication live count ${label} or minimum is not a non-negative integer: value=${value} min=${min}" >&2
    exit 1
  fi
  if (( value < min )); then
    emit_summary "FAIL" "REPLICATION_LIVE_${label}_COUNT_BELOW_MINIMUM" "${CONNECTOR_MS:-0}" "${CLAMPED_MS:-0}" "${DIRTY_STORE_MS:-0}" "${CLAMPED_FETCHES:-0}" "${CLAMPED_FALLBACKS:-0}" "${NATIVE_FLUSHES:-0}" "${DIRTY_OBJECTS:-0}" "${EXPORT_BEFORE:-0}" "${EXPORT_AFTER:-0}"
    echo "Replication live count ${label}=${value} was below required minimum ${min}." >&2
    exit 1
  fi
}

write_trend_sample() {
  local trend_file timestamp
  trend_file="${GBS_REPLICATION_LIVE_TRENDS:-}"
  if [[ -z "${trend_file}" ]]; then
    [[ -n "${GBS_EVIDENCE_DIR:-}" ]] || return 0
    trend_file="${GBS_EVIDENCE_DIR}/replication-live-trends.jsonl"
  fi
  mkdir -p "$(dirname "${trend_file}")"
  timestamp="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  printf '{"timestamp":"%s","connector_ms":%s,"clamped_ms":%s,"dirty_store_ms":%s,"clamped_traversal_fetches":%s,"clamped_traversal_fallbacks":%s,"native_dirty_store_flushes":%s,"dirty_objects_flushed":%s,"export_set_queued_after":%s}\n' \
    "${timestamp}" \
    "${CONNECTOR_MS}" \
    "${CLAMPED_MS}" \
    "${DIRTY_STORE_MS}" \
    "${CLAMPED_FETCHES}" \
    "${CLAMPED_FALLBACKS}" \
    "${NATIVE_FLUSHES}" \
    "${DIRTY_OBJECTS}" \
    "${EXPORT_AFTER}" >> "${trend_file}"
  gbs_append_summary_line "- trend sample: \`${trend_file}\`"
}

MISSING_LIVE_ENV="$(replication_missing_required_live_env_vars)"
if [[ -n "${MISSING_LIVE_ENV}" ]]; then
  emit_summary "FAIL" "REPLICATION_LIVE_MISSING_ENV"
  gbs_append_summary_line "- live env: \`required=$(replication_required_live_env_vars | paste -sd, -) missing=${MISSING_LIVE_ENV}\`"
  echo "Missing required replication live environment: ${MISSING_LIVE_ENV}" >&2
  echo "Set the missing variables before running make replication-live." >&2
  exit 2
fi

WORK_IMAGE="$(gbs_prepare_work_image "${SRC_IMAGE}" "${WORK_DIR}" "replicationlive")"
gbs_register_work_image_cleanup "${WORK_IMAGE}"

echo "Using work image: ${WORK_IMAGE}"
preflight_output="$(bash ./scripts/run_live_preflight.sh "${WORK_IMAGE}" 2>&1 || true)"
print_replication_live_excerpt "${preflight_output}"
gbs_write_evidence_file "replication-live-preflight.log" "${preflight_output}"
if ! grep -q "LIVE_PREFLIGHT_SUMMARY result=OK code=LIVE_PREFLIGHT_OK" <<< "${preflight_output}"; then
  emit_summary "FAIL" "REPLICATION_LIVE_PREFLIGHT_FAILED"
  echo "Live preflight failed or skipped; refusing to validate replication paths against an unknown GemStone session." >&2
  exit 1
fi

validation_output="$(HOME=/tmp/pharo-clean-auto/home GBS_WORK_IMAGE="${WORK_IMAGE}" "${VM}" --headless "${WORK_IMAGE}" st "/Users/tariq/src/gemtools/GemStone-Pharo-Bridge/scripts/run_replication_live_validation.st" 2>&1 || true)"
print_replication_live_excerpt "${validation_output}"
gbs_write_evidence_file "replication-live-validation.log" "${validation_output}"

summary_line="$(printf '%s\n' "${validation_output}" | grep 'REPLICATION_LIVE_VALIDATION result=' | tail -1 || true)"
if [[ -z "${summary_line}" ]]; then
  emit_summary "FAIL" "REPLICATION_LIVE_RUNNER_FAILED"
  echo "Replication live runner did not emit REPLICATION_LIVE_VALIDATION." >&2
  exit 1
fi

RESULT="$(extract_summary_field "${summary_line}" result)"
CODE="$(extract_summary_field "${summary_line}" code)"
CONNECTOR_MS="$(extract_summary_field "${summary_line}" connector_ms)"
CLAMPED_MS="$(extract_summary_field "${summary_line}" clamped_ms)"
DIRTY_STORE_MS="$(extract_summary_field "${summary_line}" dirty_store_ms)"
CLAMPED_FETCHES="$(extract_summary_field "${summary_line}" clamped_traversal_fetches)"
CLAMPED_FALLBACKS="$(extract_summary_field "${summary_line}" clamped_traversal_fallbacks)"
NATIVE_FLUSHES="$(extract_summary_field "${summary_line}" native_dirty_store_flushes)"
DIRTY_OBJECTS="$(extract_summary_field "${summary_line}" dirty_objects_flushed)"
EXPORT_BEFORE="$(extract_summary_field "${summary_line}" export_set_queued_before)"
EXPORT_AFTER="$(extract_summary_field "${summary_line}" export_set_queued_after)"

if [[ "${RESULT}" != "OK" ]]; then
  emit_summary "FAIL" "${CODE:-REPLICATION_LIVE_FAILED}" "${CONNECTOR_MS:-0}" "${CLAMPED_MS:-0}" "${DIRTY_STORE_MS:-0}" "${CLAMPED_FETCHES:-0}" "${CLAMPED_FALLBACKS:-0}" "${NATIVE_FLUSHES:-0}" "${DIRTY_OBJECTS:-0}" "${EXPORT_BEFORE:-0}" "${EXPORT_AFTER:-0}"
  echo "Replication live validation failed: ${summary_line}" >&2
  exit 1
fi

check_latency_threshold "CONNECTOR" "${CONNECTOR_MS}" "${CONNECTOR_MAX_MS}"
check_latency_threshold "CLAMPED" "${CLAMPED_MS}" "${CLAMPED_MAX_MS}"
check_latency_threshold "DIRTY_STORE" "${DIRTY_STORE_MS}" "${DIRTY_STORE_MAX_MS}"
check_count_minimum "CLAMPED_FETCHES" "${CLAMPED_FETCHES}" "${CLAMPED_FETCHES_MIN}"
check_count_threshold "CLAMPED_FETCHES" "${CLAMPED_FETCHES}" "${CLAMPED_FETCHES_MAX}"
check_count_threshold "CLAMPED_FALLBACKS" "${CLAMPED_FALLBACKS}" "${CLAMPED_FALLBACKS_MAX}"
check_count_minimum "NATIVE_DIRTY_STORE_FLUSHES" "${NATIVE_FLUSHES}" "${NATIVE_DIRTY_STORE_FLUSHES_MIN}"
check_count_minimum "DIRTY_OBJECTS_FLUSHED" "${DIRTY_OBJECTS}" "${DIRTY_OBJECTS_FLUSHED_MIN}"
check_count_threshold "EXPORT_SET_QUEUED_AFTER" "${EXPORT_AFTER}" "${EXPORT_SET_QUEUED_AFTER_MAX}"
write_trend_sample

emit_summary "OK" "REPLICATION_LIVE_OK" "${CONNECTOR_MS}" "${CLAMPED_MS}" "${DIRTY_STORE_MS}" "${CLAMPED_FETCHES}" "${CLAMPED_FALLBACKS}" "${NATIVE_FLUSHES}" "${DIRTY_OBJECTS}" "${EXPORT_BEFORE}" "${EXPORT_AFTER}"
echo "REPLICATION_LIVE_OK"
