Extension { #name : 'Object' }

{ #category : '*GemStone-GBS-Core-Tools' }
Object >> addExtensionEntryMenuItemsTo: aMenu [
	^ self
]

{ #category : '*GemStone-GBS-Core-Tools' }
Object >> addExtensionMethodMenuItemsTo: aMenuGroup [
	^ self
]

{ #category : '*GemStone-GBS-Core-Tools' }
Object >> addExtensionPreviewMenuItemsTo: aMenu [
	^ self
]

{ #category : '*GemStone-GBS-Core-Tools' }
Object >> addExtensionReportOptionsToLabels: labels actions: actions [
	^ self
]

{ #category : '*GemStone-GBS-Core-Tools' }
Object >> addExtensionSessionMenuItemsTo: aMenuGroup [
	^ self
]

{ #category : '*GemStone-GBS-Core-Tools' }
Object >> addExtensionWorkspaceMenuItemsTo: aMenuGroup [
	^ self
]

{ #category : '*GemStone-GBS-Core-Tools' }
Object >> configureExtensionStructuredInspector: presenter [
	^ self
]
